### ISSUE TITLE
Permission to use this

### ISSUE THREAD

**Issue by Gerzer** [eaw20024/Drawing-Pad#1]
I love this web app's simplicity. It would fit well in an open-source project I'm currently working on. I was wondering if I could get your permission to embed http://eaw20024.github.io/Drawing-Pad in the `index.html` file in my repository at https://github.com/Gerzer/Euclidean-algorithm using an `<iframe>`. I would be happy to give you credit and post a link to this. Thanks in advance!

**Comment by eaw20024** [comment]
Yea man, no problem! Have fun with it

**Comment by Gerzer** [comment]
Thanks!
